apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: admin-server
  name: admin-server
spec:
  ports:
  - name: "9090"
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    service: admin-server
status:
  loadBalancer: {}
