apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: config-server
  name: config-server
spec:
  ports:
  - name: "8888"
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    service: config-server
status:
  loadBalancer: {}
