apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: customers-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: customers-service
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - ./wait-for-it.sh discovery-server:8761 --timeout=60 -- java -agentpath:/opt/cdbg/cdbg_java_agent.so==--logtostderr=1
          -Dcom.google.cdbg.module=${ARTIFACT_NAME} -Dcom.google.cdbg.version=${ARTIFACT_VERSION}
          -Djava.security.egd=file:/dev/./urandom -jar /app.jar
        image: saturnism/spring-petclinic-customers-service
        name: customers-service
        ports:
        - containerPort: 8081
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
