apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: customers-service
  name: customers-service
spec:
  ports:
  - name: "8081"
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    service: customers-service
status:
  loadBalancer: {}
