apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petclinic-mysql
  labels:
    app: petclinic-mysql
spec: 
  replicas: 1
  template:
    metadata:
      labels: 
        app: petclinic-mysql
    spec:
      containers: 
      - name: mysql
        image: mysql:5.6
        resources:
          limits :
            cpu: 0.5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypassword
        - name: MYSQL_USER
          value: petclinic
        - name: MYSQL_PASSWORD
          value: yourpassword
        - name: MYSQL_DATABASE
          value: petclinic
        ports: 
        - containerPort: 3306
          name: mysql
        volumeMounts:
          # name must match the volume name below
        - name: mysql-persistent-storage
          # mount path within the container
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: petclinic-mysql-pvc
