apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: tracing-server
  name: tracing-server
spec:
  ports:
  - name: "9411"
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    service: tracing-server
status:
  loadBalancer: {}
