apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: tracing-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: tracing-server
    spec:
      containers:
      - image: gcr.io/stackdriver-trace-docker/zipkin-collector
        name: tracing-server
        ports:
        - containerPort: 9411
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
