apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: visits-service
  name: visits-service
spec:
  ports:
  - name: "8082"
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    service: visits-service
status:
  loadBalancer: {}
